### ISSUE TITLE
pkg_resources missing on fresh install

### ISSUE THREAD

**Issue by MarcinKonowalczyk** [rbanffy/pip-chill#74]
### Environment

*   PIP Chill version: 1.0.3
*   Python version: 3.12.0
*   Operating System: macos

### Description

Installing pip-chill in a fresh venv companies about the lack of `pkg_resources`. Works after `pip install setuptools`. I believe that its because setuptools is no longer added to a virtual environment by default...?

```
Traceback (most recent call last):
  File "~/.pyenv/versions/my-venv/bin/pip-chill", line 5, in <module>
    from pip_chill.cli import main
  File "~/.pyenv/versions/3.12.0/envs/my-venv/lib/python3.12/site-packages/pip_chill/__init__.py", line 3, in <module>
    from .pip_chill import chill
  File "~/.pyenv/versions/3.12.0/envs/my-venv/lib/python3.12/site-packages/pip_chill/pip_chill.py", line 4, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

Short-term solution would be to add setuptools as a dependency(?), but longer-term maybe worth switching to `importllib.resources` (and `importlib_resources` backport) just like [setuptools reccomends](https://setuptools.pypa.io/en/latest/pkg_resources.html)?

**Comment by MarcinKonowalczyk** [comment]
bump

**Comment by Drblessing** [comment]
bump

**Comment by bcrotty** [comment]
Same issue here except with a fresh system install of 3.12.2. As mentioned by OP, installing setuptools fixes this.

**Comment by MarcinKonowalczyk** [comment]
bump

**Comment by MarcinKonowalczyk** [comment]
ok, fine. as opposed to just bump'ing, see PR #75

**Comment by MarcinKonowalczyk** [comment]
bump (actually work-in-progress 👍)

**Comment by pfeif** [comment]
Just as a heads-up, this is still an issue in Python 3.12.6 on Windows 10.

```
pip install pip-chill
pip-chill
```

results in

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "<my project path>\.venv\Scripts\pip-chill.exe\__main__.py", line 4, in <module>
  File "<my project path>\.venv\Lib\site-packages\pip_chill\__init__.py", line 3, in <module>
    from .pip_chill import chill
  File "<my project path>\.venv\Lib\site-packages\pip_chill\pip_chill.py", line 4, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

Manually installing setuptools resolves the error.
